#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 2

#define HOLD_ON_OTHER_KEY_PRESS

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#ifdef COMBO_ENABLE
#define COMBO_MUST_HOLD_MODS
#define COMBO_ONLY_FROM_LAYER 0
#endif
